#!/bin/sh
printf '    *****MAKE ************************\n'
make sample  && chmod +x sample && 
printf '    *****RUN  ************************\n'&&
./sample
printf '*********DONE ************************\n'
